spring.application.name=03_microservicio_personas_simple
# Configuracion de la base de datos H2 contra una base de datos en memoria llamada "personasdb"
spring.datasource.url=jdbc:h2:mem:personasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Configuracion de JPA para crear automaticamente las tablas basadas en las entidades
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL en la consola para depuracion
spring.jpa.show-sql=true
# Datos de conexion para la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8000
